### PR TITLE
Fix defaults for STDOUT and Conf.stream_params

### PR DESCRIPTION
**Pull request by darvelo**
Provides a workable default for `Conf.stream_params` if a conf file
doesn't exist in the user's home directory. Would crash otherwise.

Thanks for the great script! :+1:

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks!

I didn't really test mk2 with crashing and restarting pulseaudio, so there indeed be dragons like the one you spotted.

**Comment by darvelo** [comment]
No problemo!

It didn't crash pulseaudio I don't think, the program just exited with an Exception because it tried to access a dictionary that wasn't there unless the config file existed. Slaying dragons is fun!

**Comment by mk-fg** [comment]
Heh, right, though I meant that obvious STDOUT bug, which I clearly never hit myself because I never had PA started from mk2 script.

Iirc there were some issues with dbus-python behaving quite weird (to the point of being unrecoverable) when pulseaudio suddenly dies, but these should be trivial to resolve, as all dbus-python stuff happens in glib child anyway, which can be restarted in the worst-case.

One other thing that can be tested here is whether PA has dbus module ready when it forks these days, don't think it was the case with early 1.0devX versions, hence the commented-out delay there.

**Comment by darvelo** [comment]
That's true. Haha, during my first changes I remember pulse doing some very weird things. I must have crashed it somehow.

I don't know enough about dbus and pulseaudio to work the magic that you do here, so I'm glad you were able to solve all this stuff.

**Pull request merged**
